### ISSUE TITLE
new pypi release

### ISSUE THREAD

**Issue by sijis** [tedops/party#6]
Hi,

Are there any plans to update the release of party that is on pypi? The version currently out there is over a year old.

**Comment by tedops** [comment]
Hi - yes indeed there are. I'm in the middle of a rewrite, which is centered on tests and uses Python 3. I'm aiming to have a new one on pypi by end of Jan. Thanks again for your PR!

**Comment by sijis** [comment]
I do think there is value in updating pypi with a new release. One of the biggest reasons is that it shows the project is active. Even if you desire and finish in a few months, its been 1.5 years and no updates.

The other  factor is that existing users can get new functionality that's been added since the last release.

On A separate note, I was already tinkering with changing some method responses. Instead of just returning 'ok'. It would actually return the results. So even if there were no results, you should get something back, even if it's an empty list/dict.
The reason is that at first I didn't realize the results of method calls created  new property with the results.

**Comment by tedops** [comment]
@sijis Agreed on releasing a new version despite personal progress. I'll tag latest and push a new package to pypi.python.org. Thanks!

**Comment by tedops** [comment]
@sijis Party 1.6.2 is now available on http://pypi.python.org. :+1:

**Comment by sijis** [comment]
Super awesome!! Thanks.
I just realized I didn't update the readme on the config param.
